--drop table producto;

CREATE TABLE PRODUCTO(
    PRODUCTO_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(240) NOT NULL UNIQUE,
    PRECIO NUMERIC(6,2) NOT NULL,
    STOCK NUMERIC(4) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL 
);